name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  speed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build

      - name: Speed-output
        run: find -maxdepth 1 -type d -name 'day*' -not -name day00 | sort | xargs --replace bash -xc 'python {}/part1.py {}/input.txt; python {}/part2.py {}/input.txt'
